import type { StrategyDefinition } from "./types";

// Reference/demo pricing only. These values are deliberately isolated so they can
// later be replaced with a pricing API without changing the evaluation engine.
export const STRATEGIES: StrategyDefinition[] = [
  {
    id: "lakeflow-serverless",
    shortName: "Serverless",
    name: "Lakeflow Declarative Pipelines Serverless",
    category: "Managed pipeline",
    description: "Fully managed compute with rapid startup and minimal infrastructure overhead.",
    supports: ["streaming", "batch"],
    supportsPrivateNetworking: false,
    minimumSlaMinutes: 5,
    baseMonthlyCost: 180,
    computeRate: 0.78,
    volumeRate: 0.045,
    operationalScore: 24,
    advantages: ["Lowest operational overhead", "Fast autoscaling", "Simple capacity management"],
    disadvantages: ["Private networking unsupported in this demo model", "Less compute-level control"],
  },
  {
    id: "lakeflow-classic",
    shortName: "Classic",
    name: "Lakeflow Declarative Pipelines Classic",
    category: "Managed pipeline",
    description: "Pipeline orchestration with configurable compute and network controls.",
    supports: ["streaming", "batch"],
    supportsPrivateNetworking: true,
    minimumSlaMinutes: 5,
    baseMonthlyCost: 220,
    computeRate: 1.15,
    volumeRate: 0.03,
    operationalScore: 18,
    advantages: ["Supports private networking", "Strong streaming semantics", "Configurable compute"],
    disadvantages: ["More operations than serverless", "Higher always-on baseline"],
  },
  {
    id: "lakeflow-jobs",
    shortName: "Job compute",
    name: "Lakeflow Jobs / Job Compute",
    category: "Scheduled compute",
    description: "Flexible job compute optimized for scheduled, finite data processing runs.",
    supports: ["batch", "streaming"],
    supportsPrivateNetworking: true,
    minimumSlaMinutes: 15,
    baseMonthlyCost: 90,
    computeRate: 0.92,
    volumeRate: 0.025,
    operationalScore: 14,
    advantages: ["Cost-effective for bounded runs", "Supports private networking", "Flexible job orchestration"],
    disadvantages: ["Not suited to a sub-15-minute streaming SLA", "More orchestration responsibility"],
  },
];
