import type { StrategyDefinition, WorkloadCategory } from "./types";

export const STRATEGIES: StrategyDefinition[] = [
  {
    id: "serverless-sql",
    shortName: "Serverless",
    name: "Databricks SQL Serverless",
    category: "SQL warehouse",
    workloadType: "DWH",
    description: "Managed SQL compute with rapid startup, elastic scaling, and infrastructure included in the DBU rate.",
    supportsPrivateNetworking: false,
    operationalScore: 25,
    performanceLabel: "Elastic auto-scale",
    performanceDetail: "Rapid startup and responsive scaling",
    operationalEffort: "Low",
    operationalDetail: "Fully managed infrastructure",
    bestFor: "Variable demand, low-latency BI, and quick starts",
    advantages: ["Lowest operational overhead", "Fast autoscaling", "Simple capacity management"],
    disadvantages: ["Private networking unsupported in this planning model", "Less compute-level control"],
  },
  {
    id: "pro-sql",
    shortName: "Pro",
    name: "Databricks SQL Pro",
    category: "SQL warehouse",
    workloadType: "DWH",
    description: "Advanced SQL performance with configurable compute inside your cloud account and custom networking.",
    supportsPrivateNetworking: true,
    operationalScore: 18,
    performanceLabel: "Threshold auto-scale",
    performanceDetail: "High-concurrency SQL with performance controls",
    operationalEffort: "Medium",
    operationalDetail: "Compute runs inside your cloud account",
    bestFor: "Custom networking and high-concurrency BI/SQL",
    advantages: ["Supports private networking", "Predictive I/O", "Configurable compute"],
    disadvantages: ["Slower startup than serverless", "Cloud VM charges are additional"],
  },
  {
    id: "classic-sql",
    shortName: "Classic",
    name: "Databricks SQL Classic",
    category: "SQL warehouse",
    workloadType: "DWH",
    description: "A straightforward warehouse for established setups and basic interactive workloads.",
    supportsPrivateNetworking: true,
    operationalScore: 12,
    performanceLabel: "Threshold auto-scale",
    performanceDetail: "Predictable scaling for established workloads",
    operationalEffort: "Medium",
    operationalDetail: "More infrastructure and scaling responsibility",
    bestFor: "Basic exploration and established Classic deployments",
    advantages: ["Lowest DBU list rate", "Supports private networking", "Familiar infrastructure controls"],
    disadvantages: ["Basic SQL feature set", "Cloud VM charges are additional"],
  },
  {
    id: "jobs-serverless",
    shortName: "Serverless Jobs",
    name: "Databricks Jobs Serverless",
    category: "ETL compute",
    workloadType: "ETL",
    description: "Managed job compute billed by emitted DBUs without separate cloud VM charges.",
    supportsPrivateNetworking: false,
    operationalScore: 24,
    performanceLabel: "Elastic auto-scale",
    performanceDetail: "Managed capacity for bursty jobs",
    operationalEffort: "Low",
    operationalDetail: "No cluster lifecycle management",
    bestFor: "Bursty ETL and teams minimizing infrastructure work",
    advantages: ["Minimal infrastructure work", "Infrastructure included", "Fast elastic scaling"],
    disadvantages: ["Private networking unsupported in this planning model", "Less instance-level control"],
  },
  {
    id: "jobs-classic",
    shortName: "Classic Jobs",
    name: "Databricks Jobs Classic",
    category: "ETL compute",
    workloadType: "ETL",
    description: "Driver and worker compute in your cloud account with explicit instance and network control.",
    supportsPrivateNetworking: true,
    operationalScore: 15,
    performanceLabel: "Configurable scale",
    performanceDetail: "Explicit driver and worker sizing",
    operationalEffort: "Medium",
    operationalDetail: "Cluster policies and lifecycle management",
    bestFor: "Private networks and predictable production pipelines",
    advantages: ["Supports private networking", "Explicit instance sizing", "Flexible cluster policies"],
    disadvantages: ["Separate VM charges", "More infrastructure responsibility"],
  },
  {
    id: "all-purpose-classic",
    shortName: "All-Purpose",
    name: "Classic All-Purpose Compute",
    category: "Development compute",
    workloadType: "DEV",
    description: "Interactive driver and worker compute for notebooks and development workflows.",
    supportsPrivateNetworking: true,
    operationalScore: 14,
    performanceLabel: "Interactive scale",
    performanceDetail: "Persistent capacity for iterative development",
    operationalEffort: "High",
    operationalDetail: "Interactive cluster lifecycle and idle capacity",
    bestFor: "Notebook development and collaborative exploration",
    advantages: ["Interactive development", "Explicit instance sizing", "Supports private networking"],
    disadvantages: ["Separate VM charges", "Not optimized for scheduled production jobs"],
  },
];

export function getStrategiesForWorkload(type: WorkloadCategory): StrategyDefinition[] {
  return STRATEGIES.filter((strategy) => strategy.workloadType === type);
}
